\ir ../functions/init/normalize_territory_name.sql
\ir ../functions/init/validate_turnout_result.sql
\ir ../functions/init/validate_vote_result.sql
\ir ../functions/init/refresh_result_summary_for_context.sql
\ir ../functions/init/refresh_result_summary_after_change.sql
\ir ../functions/init/save_political_entity.sql
\ir ../functions/init/save_turnout_result.sql
\ir ../functions/init/save_candidacy_vote_result.sql
\ir ../functions/spatial/country.sql
\ir ../functions/spatial/district_municipalities.sql
\ir ../functions/spatial/municipality_parishes.sql
\ir ../functions/spatial/parish.sql
