\ir ../functions/analytics/resolve_vote_territory.sql
\ir ../functions/analytics/resolve_match_territory.sql
\ir ../functions/analytics/get_political_side.sql
\ir ../functions/analytics/party_results.sql
\ir ../functions/analytics/results_for_territory_parties.sql
\ir ../functions/analytics/result_for_territory.sql
\ir ../functions/analytics/abstention_for_territory.sql
\ir ../functions/analytics/rise_and_fall.sql
\ir ../functions/analytics/vote_swing_by_territory.sql
